global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "hive.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: hive
    static_configs:
      - targets: ['localhost:9100']

  - job_name: osxguest
    static_configs:
      - targets: ['osx.hive.dolphin-emu.org:9100']

  - job_name: winguest
    static_configs:
      - targets: ['win.hive.dolphin-emu.org:9182']

  - job_name: buildbot
    static_configs:
      - targets: ['localhost:8011']

alerting:
  alertmanagers:
  - static_configs:
      - targets: ['localhost:9093']
